//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LePrAtos.GameManagerService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.org/")]
    public partial class MyExceptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(player))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.org/")]
    public partial class playerIdentification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool statusField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.org/")]
    public partial class player : playerIdentification {
        
        private string emailField;
        
        private string passwordField;
        
        private string playerIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string playerID {
            get {
                return this.playerIDField;
            }
            set {
                this.playerIDField = value;
                this.RaisePropertyChanged("playerID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.org/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.org/", ConfigurationName="GameManagerService.GameManager")]
    public interface GameManager {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/username_availabilityRequest", ReplyAction="http://webservices.org/GameManager/username_availabilityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.username_availabilityResponse username_availability(LePrAtos.GameManagerService.username_availabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/username_availabilityRequest", ReplyAction="http://webservices.org/GameManager/username_availabilityResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.username_availabilityResponse> username_availabilityAsync(LePrAtos.GameManagerService.username_availabilityRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/email_verificationRequest", ReplyAction="http://webservices.org/GameManager/email_verificationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.email_verificationResponse email_verification(LePrAtos.GameManagerService.email_verificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/email_verificationRequest", ReplyAction="http://webservices.org/GameManager/email_verificationResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.email_verificationResponse> email_verificationAsync(LePrAtos.GameManagerService.email_verificationRequest request);
        
        // CODEGEN: Parameter 'playerID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/setGameLobbyPasswordRequest", ReplyAction="http://webservices.org/GameManager/setGameLobbyPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        LePrAtos.GameManagerService.setGameLobbyPasswordResponse setGameLobbyPassword(LePrAtos.GameManagerService.setGameLobbyPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/setGameLobbyPasswordRequest", ReplyAction="http://webservices.org/GameManager/setGameLobbyPasswordResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.setGameLobbyPasswordResponse> setGameLobbyPasswordAsync(LePrAtos.GameManagerService.setGameLobbyPasswordRequest request);
        
        // CODEGEN: Parameter 'playerID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/resetGameLobbyPasswordRequest", ReplyAction="http://webservices.org/GameManager/resetGameLobbyPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        LePrAtos.GameManagerService.resetGameLobbyPasswordResponse resetGameLobbyPassword(LePrAtos.GameManagerService.resetGameLobbyPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/resetGameLobbyPasswordRequest", ReplyAction="http://webservices.org/GameManager/resetGameLobbyPasswordResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.resetGameLobbyPasswordResponse> resetGameLobbyPasswordAsync(LePrAtos.GameManagerService.resetGameLobbyPasswordRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/registrationRequest", ReplyAction="http://webservices.org/GameManager/registrationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.registrationResponse registration(LePrAtos.GameManagerService.registrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/registrationRequest", ReplyAction="http://webservices.org/GameManager/registrationResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.registrationResponse> registrationAsync(LePrAtos.GameManagerService.registrationRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/loginRequest", ReplyAction="http://webservices.org/GameManager/loginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LePrAtos.GameManagerService.MyExceptions), Action="http://webservices.org/GameManager/login/Fault/MyExceptions", Name="MyExceptions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.loginResponse login(LePrAtos.GameManagerService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/loginRequest", ReplyAction="http://webservices.org/GameManager/loginResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.loginResponse> loginAsync(LePrAtos.GameManagerService.loginRequest request);
        
        // CODEGEN: Parameter 'playerID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/logoutRequest", ReplyAction="http://webservices.org/GameManager/logoutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        LePrAtos.GameManagerService.logoutResponse logout(LePrAtos.GameManagerService.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/logoutRequest", ReplyAction="http://webservices.org/GameManager/logoutResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.logoutResponse> logoutAsync(LePrAtos.GameManagerService.logoutRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/createGameLobbyRequest", ReplyAction="http://webservices.org/GameManager/createGameLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LePrAtos.GameManagerService.Exception), Action="http://webservices.org/GameManager/createGameLobby/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.createGameLobbyResponse createGameLobby(LePrAtos.GameManagerService.createGameLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/createGameLobbyRequest", ReplyAction="http://webservices.org/GameManager/createGameLobbyResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.createGameLobbyResponse> createGameLobbyAsync(LePrAtos.GameManagerService.createGameLobbyRequest request);
        
        // CODEGEN: Parameter 'playerID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/setGameLobbyNameRequest", ReplyAction="http://webservices.org/GameManager/setGameLobbyNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        LePrAtos.GameManagerService.setGameLobbyNameResponse setGameLobbyName(LePrAtos.GameManagerService.setGameLobbyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/setGameLobbyNameRequest", ReplyAction="http://webservices.org/GameManager/setGameLobbyNameResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.setGameLobbyNameResponse> setGameLobbyNameAsync(LePrAtos.GameManagerService.setGameLobbyNameRequest request);
        
        // CODEGEN: Parameter 'playerID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/setPlayerLimitRequest", ReplyAction="http://webservices.org/GameManager/setPlayerLimitResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        LePrAtos.GameManagerService.setPlayerLimitResponse setPlayerLimit(LePrAtos.GameManagerService.setPlayerLimitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/setPlayerLimitRequest", ReplyAction="http://webservices.org/GameManager/setPlayerLimitResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.setPlayerLimitResponse> setPlayerLimitAsync(LePrAtos.GameManagerService.setPlayerLimitRequest request);
        
        // CODEGEN: Parameter 'playerID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/kickPlayerRequest", ReplyAction="http://webservices.org/GameManager/kickPlayerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        LePrAtos.GameManagerService.kickPlayerResponse kickPlayer(LePrAtos.GameManagerService.kickPlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/kickPlayerRequest", ReplyAction="http://webservices.org/GameManager/kickPlayerResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.kickPlayerResponse> kickPlayerAsync(LePrAtos.GameManagerService.kickPlayerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/joinGameLobbyRequest", ReplyAction="http://webservices.org/GameManager/joinGameLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LePrAtos.GameManagerService.Exception), Action="http://webservices.org/GameManager/joinGameLobby/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.joinGameLobbyResponse joinGameLobby(LePrAtos.GameManagerService.joinGameLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/joinGameLobbyRequest", ReplyAction="http://webservices.org/GameManager/joinGameLobbyResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.joinGameLobbyResponse> joinGameLobbyAsync(LePrAtos.GameManagerService.joinGameLobbyRequest request);
        
        // CODEGEN: Parameter 'playerID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/leaveGameLobbyRequest", ReplyAction="http://webservices.org/GameManager/leaveGameLobbyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        LePrAtos.GameManagerService.leaveGameLobbyResponse leaveGameLobby(LePrAtos.GameManagerService.leaveGameLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/leaveGameLobbyRequest", ReplyAction="http://webservices.org/GameManager/leaveGameLobbyResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.leaveGameLobbyResponse> leaveGameLobbyAsync(LePrAtos.GameManagerService.leaveGameLobbyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/getGameLobbyRequest", ReplyAction="http://webservices.org/GameManager/getGameLobbyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.getGameLobbyResponse getGameLobby(LePrAtos.GameManagerService.getGameLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/getGameLobbyRequest", ReplyAction="http://webservices.org/GameManager/getGameLobbyResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.getGameLobbyResponse> getGameLobbyAsync(LePrAtos.GameManagerService.getGameLobbyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/getGameLobbiesRequest", ReplyAction="http://webservices.org/GameManager/getGameLobbiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.getGameLobbiesResponse getGameLobbies(LePrAtos.GameManagerService.getGameLobbiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/getGameLobbiesRequest", ReplyAction="http://webservices.org/GameManager/getGameLobbiesResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.getGameLobbiesResponse> getGameLobbiesAsync(LePrAtos.GameManagerService.getGameLobbiesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/getPlayerByIDRequest", ReplyAction="http://webservices.org/GameManager/getPlayerByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LePrAtos.GameManagerService.getPlayerByIDResponse getPlayerByID(LePrAtos.GameManagerService.getPlayerByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/getPlayerByIDRequest", ReplyAction="http://webservices.org/GameManager/getPlayerByIDResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.getPlayerByIDResponse> getPlayerByIDAsync(LePrAtos.GameManagerService.getPlayerByIDRequest request);
        
        // CODEGEN: Parameter 'playerID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/setPlayerStatusRequest", ReplyAction="http://webservices.org/GameManager/setPlayerStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(playerIdentification))]
        LePrAtos.GameManagerService.setPlayerStatusResponse setPlayerStatus(LePrAtos.GameManagerService.setPlayerStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.org/GameManager/setPlayerStatusRequest", ReplyAction="http://webservices.org/GameManager/setPlayerStatusResponse")]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.setPlayerStatusResponse> setPlayerStatusAsync(LePrAtos.GameManagerService.setPlayerStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="username_availability", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class username_availabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public username_availabilityRequest() {
        }
        
        public username_availabilityRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="username_availabilityResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class username_availabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public username_availabilityResponse() {
        }
        
        public username_availabilityResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="email_verification", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class email_verificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public email_verificationRequest() {
        }
        
        public email_verificationRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="email_verificationResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class email_verificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public email_verificationResponse() {
        }
        
        public email_verificationResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setGameLobbyPassword", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class setGameLobbyPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameLobbyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gameLobbyPassword;
        
        public setGameLobbyPasswordRequest() {
        }
        
        public setGameLobbyPasswordRequest(string playerID, string GameLobbyID, string gameLobbyPassword) {
            this.playerID = playerID;
            this.GameLobbyID = GameLobbyID;
            this.gameLobbyPassword = gameLobbyPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setGameLobbyPasswordResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class setGameLobbyPasswordResponse {
        
        public setGameLobbyPasswordResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resetGameLobbyPassword", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class resetGameLobbyPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameLobbyID;
        
        public resetGameLobbyPasswordRequest() {
        }
        
        public resetGameLobbyPasswordRequest(string playerID, string GameLobbyID) {
            this.playerID = playerID;
            this.GameLobbyID = GameLobbyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resetGameLobbyPasswordResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class resetGameLobbyPasswordResponse {
        
        public resetGameLobbyPasswordResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registration", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class registrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public registrationRequest() {
        }
        
        public registrationRequest(string email, string username, string password) {
            this.email = email;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrationResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class registrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LePrAtos.GameManagerService.player @return;
        
        public registrationResponse() {
        }
        
        public registrationResponse(LePrAtos.GameManagerService.player @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username_email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public loginRequest() {
        }
        
        public loginRequest(string username_email, string password) {
            this.username_email = username_email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LePrAtos.GameManagerService.player @return;
        
        public loginResponse() {
        }
        
        public loginResponse(LePrAtos.GameManagerService.player @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logout", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        public logoutRequest() {
        }
        
        public logoutRequest(string playerID) {
            this.playerID = playerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logoutResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class logoutResponse {
        
        public logoutResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.org/")]
    public partial class gameLobby : object, System.ComponentModel.INotifyPropertyChanged {
        
        private playerIdentification gameLobbyAdminField;
        
        private string gameLobbyIDField;
        
        private string gameLobbyNameField;
        
        private playerIdentification[] gamePlayerListField;
        
        private bool passwordProtectedField;
        
        private int playerLimitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public playerIdentification gameLobbyAdmin {
            get {
                return this.gameLobbyAdminField;
            }
            set {
                this.gameLobbyAdminField = value;
                this.RaisePropertyChanged("gameLobbyAdmin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gameLobbyID {
            get {
                return this.gameLobbyIDField;
            }
            set {
                this.gameLobbyIDField = value;
                this.RaisePropertyChanged("gameLobbyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string gameLobbyName {
            get {
                return this.gameLobbyNameField;
            }
            set {
                this.gameLobbyNameField = value;
                this.RaisePropertyChanged("gameLobbyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gamePlayerList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public playerIdentification[] gamePlayerList {
            get {
                return this.gamePlayerListField;
            }
            set {
                this.gamePlayerListField = value;
                this.RaisePropertyChanged("gamePlayerList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool passwordProtected {
            get {
                return this.passwordProtectedField;
            }
            set {
                this.passwordProtectedField = value;
                this.RaisePropertyChanged("passwordProtected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int playerLimit {
            get {
                return this.playerLimitField;
            }
            set {
                this.playerLimitField = value;
                this.RaisePropertyChanged("playerLimit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createGameLobby", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class createGameLobbyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gameLobbyName;
        
        public createGameLobbyRequest() {
        }
        
        public createGameLobbyRequest(string playerID, string gameLobbyName) {
            this.playerID = playerID;
            this.gameLobbyName = gameLobbyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createGameLobbyResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class createGameLobbyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LePrAtos.GameManagerService.gameLobby @return;
        
        public createGameLobbyResponse() {
        }
        
        public createGameLobbyResponse(LePrAtos.GameManagerService.gameLobby @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setGameLobbyName", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class setGameLobbyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameLobbyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gameLobbyName;
        
        public setGameLobbyNameRequest() {
        }
        
        public setGameLobbyNameRequest(string playerID, string GameLobbyID, string gameLobbyName) {
            this.playerID = playerID;
            this.GameLobbyID = GameLobbyID;
            this.gameLobbyName = gameLobbyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setGameLobbyNameResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class setGameLobbyNameResponse {
        
        public setGameLobbyNameResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPlayerLimit", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class setPlayerLimitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameLobbyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int playerLimit;
        
        public setPlayerLimitRequest() {
        }
        
        public setPlayerLimitRequest(string playerID, string GameLobbyID, int playerLimit) {
            this.playerID = playerID;
            this.GameLobbyID = GameLobbyID;
            this.playerLimit = playerLimit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPlayerLimitResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class setPlayerLimitResponse {
        
        public setPlayerLimitResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kickPlayer", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class kickPlayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameLobbyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public kickPlayerRequest() {
        }
        
        public kickPlayerRequest(string playerID, string GameLobbyID, string username) {
            this.playerID = playerID;
            this.GameLobbyID = GameLobbyID;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kickPlayerResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class kickPlayerResponse {
        
        public kickPlayerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="joinGameLobby", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class joinGameLobbyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameLobbyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gameLobbyPassword;
        
        public joinGameLobbyRequest() {
        }
        
        public joinGameLobbyRequest(string playerID, string GameLobbyID, string gameLobbyPassword) {
            this.playerID = playerID;
            this.GameLobbyID = GameLobbyID;
            this.gameLobbyPassword = gameLobbyPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="joinGameLobbyResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class joinGameLobbyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LePrAtos.GameManagerService.gameLobby @return;
        
        public joinGameLobbyResponse() {
        }
        
        public joinGameLobbyResponse(LePrAtos.GameManagerService.gameLobby @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leaveGameLobby", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class leaveGameLobbyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameLobbyID;
        
        public leaveGameLobbyRequest() {
        }
        
        public leaveGameLobbyRequest(string playerID, string GameLobbyID) {
            this.playerID = playerID;
            this.GameLobbyID = GameLobbyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leaveGameLobbyResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class leaveGameLobbyResponse {
        
        public leaveGameLobbyResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGameLobby", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class getGameLobbyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameLobbyID;
        
        public getGameLobbyRequest() {
        }
        
        public getGameLobbyRequest(string GameLobbyID) {
            this.GameLobbyID = GameLobbyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGameLobbyResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class getGameLobbyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LePrAtos.GameManagerService.gameLobby @return;
        
        public getGameLobbyResponse() {
        }
        
        public getGameLobbyResponse(LePrAtos.GameManagerService.gameLobby @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGameLobbies", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class getGameLobbiesRequest {
        
        public getGameLobbiesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGameLobbiesResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class getGameLobbiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LePrAtos.GameManagerService.gameLobby[] @return;
        
        public getGameLobbiesResponse() {
        }
        
        public getGameLobbiesResponse(LePrAtos.GameManagerService.gameLobby[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPlayerByID", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class getPlayerByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        public getPlayerByIDRequest() {
        }
        
        public getPlayerByIDRequest(string playerID) {
            this.playerID = playerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPlayerByIDResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class getPlayerByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LePrAtos.GameManagerService.player @return;
        
        public getPlayerByIDResponse() {
        }
        
        public getPlayerByIDResponse(LePrAtos.GameManagerService.player @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPlayerStatus", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class setPlayerStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string playerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public setPlayerStatusRequest() {
        }
        
        public setPlayerStatusRequest(string playerID, bool status) {
            this.playerID = playerID;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPlayerStatusResponse", WrapperNamespace="http://webservices.org/", IsWrapped=true)]
    public partial class setPlayerStatusResponse {
        
        public setPlayerStatusResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GameManagerChannel : LePrAtos.GameManagerService.GameManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameManagerClient : System.ServiceModel.ClientBase<LePrAtos.GameManagerService.GameManager>, LePrAtos.GameManagerService.GameManager {
        
        public GameManagerClient() {
        }
        
        public GameManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.username_availabilityResponse LePrAtos.GameManagerService.GameManager.username_availability(LePrAtos.GameManagerService.username_availabilityRequest request) {
            return base.Channel.username_availability(request);
        }
        
        public bool username_availability(string username) {
            LePrAtos.GameManagerService.username_availabilityRequest inValue = new LePrAtos.GameManagerService.username_availabilityRequest();
            inValue.username = username;
            LePrAtos.GameManagerService.username_availabilityResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).username_availability(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.username_availabilityResponse> LePrAtos.GameManagerService.GameManager.username_availabilityAsync(LePrAtos.GameManagerService.username_availabilityRequest request) {
            return base.Channel.username_availabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.username_availabilityResponse> username_availabilityAsync(string username) {
            LePrAtos.GameManagerService.username_availabilityRequest inValue = new LePrAtos.GameManagerService.username_availabilityRequest();
            inValue.username = username;
            return ((LePrAtos.GameManagerService.GameManager)(this)).username_availabilityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.email_verificationResponse LePrAtos.GameManagerService.GameManager.email_verification(LePrAtos.GameManagerService.email_verificationRequest request) {
            return base.Channel.email_verification(request);
        }
        
        public bool email_verification(string email) {
            LePrAtos.GameManagerService.email_verificationRequest inValue = new LePrAtos.GameManagerService.email_verificationRequest();
            inValue.email = email;
            LePrAtos.GameManagerService.email_verificationResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).email_verification(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.email_verificationResponse> LePrAtos.GameManagerService.GameManager.email_verificationAsync(LePrAtos.GameManagerService.email_verificationRequest request) {
            return base.Channel.email_verificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.email_verificationResponse> email_verificationAsync(string email) {
            LePrAtos.GameManagerService.email_verificationRequest inValue = new LePrAtos.GameManagerService.email_verificationRequest();
            inValue.email = email;
            return ((LePrAtos.GameManagerService.GameManager)(this)).email_verificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.setGameLobbyPasswordResponse LePrAtos.GameManagerService.GameManager.setGameLobbyPassword(LePrAtos.GameManagerService.setGameLobbyPasswordRequest request) {
            return base.Channel.setGameLobbyPassword(request);
        }
        
        public void setGameLobbyPassword(string playerID, string GameLobbyID, string gameLobbyPassword) {
            LePrAtos.GameManagerService.setGameLobbyPasswordRequest inValue = new LePrAtos.GameManagerService.setGameLobbyPasswordRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.gameLobbyPassword = gameLobbyPassword;
            LePrAtos.GameManagerService.setGameLobbyPasswordResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).setGameLobbyPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.setGameLobbyPasswordResponse> LePrAtos.GameManagerService.GameManager.setGameLobbyPasswordAsync(LePrAtos.GameManagerService.setGameLobbyPasswordRequest request) {
            return base.Channel.setGameLobbyPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.setGameLobbyPasswordResponse> setGameLobbyPasswordAsync(string playerID, string GameLobbyID, string gameLobbyPassword) {
            LePrAtos.GameManagerService.setGameLobbyPasswordRequest inValue = new LePrAtos.GameManagerService.setGameLobbyPasswordRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.gameLobbyPassword = gameLobbyPassword;
            return ((LePrAtos.GameManagerService.GameManager)(this)).setGameLobbyPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.resetGameLobbyPasswordResponse LePrAtos.GameManagerService.GameManager.resetGameLobbyPassword(LePrAtos.GameManagerService.resetGameLobbyPasswordRequest request) {
            return base.Channel.resetGameLobbyPassword(request);
        }
        
        public void resetGameLobbyPassword(string playerID, string GameLobbyID) {
            LePrAtos.GameManagerService.resetGameLobbyPasswordRequest inValue = new LePrAtos.GameManagerService.resetGameLobbyPasswordRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            LePrAtos.GameManagerService.resetGameLobbyPasswordResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).resetGameLobbyPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.resetGameLobbyPasswordResponse> LePrAtos.GameManagerService.GameManager.resetGameLobbyPasswordAsync(LePrAtos.GameManagerService.resetGameLobbyPasswordRequest request) {
            return base.Channel.resetGameLobbyPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.resetGameLobbyPasswordResponse> resetGameLobbyPasswordAsync(string playerID, string GameLobbyID) {
            LePrAtos.GameManagerService.resetGameLobbyPasswordRequest inValue = new LePrAtos.GameManagerService.resetGameLobbyPasswordRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            return ((LePrAtos.GameManagerService.GameManager)(this)).resetGameLobbyPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.registrationResponse LePrAtos.GameManagerService.GameManager.registration(LePrAtos.GameManagerService.registrationRequest request) {
            return base.Channel.registration(request);
        }
        
        public LePrAtos.GameManagerService.player registration(string email, string username, string password) {
            LePrAtos.GameManagerService.registrationRequest inValue = new LePrAtos.GameManagerService.registrationRequest();
            inValue.email = email;
            inValue.username = username;
            inValue.password = password;
            LePrAtos.GameManagerService.registrationResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).registration(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.registrationResponse> LePrAtos.GameManagerService.GameManager.registrationAsync(LePrAtos.GameManagerService.registrationRequest request) {
            return base.Channel.registrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.registrationResponse> registrationAsync(string email, string username, string password) {
            LePrAtos.GameManagerService.registrationRequest inValue = new LePrAtos.GameManagerService.registrationRequest();
            inValue.email = email;
            inValue.username = username;
            inValue.password = password;
            return ((LePrAtos.GameManagerService.GameManager)(this)).registrationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.loginResponse LePrAtos.GameManagerService.GameManager.login(LePrAtos.GameManagerService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public LePrAtos.GameManagerService.player login(string username_email, string password) {
            LePrAtos.GameManagerService.loginRequest inValue = new LePrAtos.GameManagerService.loginRequest();
            inValue.username_email = username_email;
            inValue.password = password;
            LePrAtos.GameManagerService.loginResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.loginResponse> LePrAtos.GameManagerService.GameManager.loginAsync(LePrAtos.GameManagerService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.loginResponse> loginAsync(string username_email, string password) {
            LePrAtos.GameManagerService.loginRequest inValue = new LePrAtos.GameManagerService.loginRequest();
            inValue.username_email = username_email;
            inValue.password = password;
            return ((LePrAtos.GameManagerService.GameManager)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.logoutResponse LePrAtos.GameManagerService.GameManager.logout(LePrAtos.GameManagerService.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public void logout(string playerID) {
            LePrAtos.GameManagerService.logoutRequest inValue = new LePrAtos.GameManagerService.logoutRequest();
            inValue.playerID = playerID;
            LePrAtos.GameManagerService.logoutResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.logoutResponse> LePrAtos.GameManagerService.GameManager.logoutAsync(LePrAtos.GameManagerService.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.logoutResponse> logoutAsync(string playerID) {
            LePrAtos.GameManagerService.logoutRequest inValue = new LePrAtos.GameManagerService.logoutRequest();
            inValue.playerID = playerID;
            return ((LePrAtos.GameManagerService.GameManager)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.createGameLobbyResponse LePrAtos.GameManagerService.GameManager.createGameLobby(LePrAtos.GameManagerService.createGameLobbyRequest request) {
            return base.Channel.createGameLobby(request);
        }
        
        public LePrAtos.GameManagerService.gameLobby createGameLobby(string playerID, string gameLobbyName) {
            LePrAtos.GameManagerService.createGameLobbyRequest inValue = new LePrAtos.GameManagerService.createGameLobbyRequest();
            inValue.playerID = playerID;
            inValue.gameLobbyName = gameLobbyName;
            LePrAtos.GameManagerService.createGameLobbyResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).createGameLobby(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.createGameLobbyResponse> LePrAtos.GameManagerService.GameManager.createGameLobbyAsync(LePrAtos.GameManagerService.createGameLobbyRequest request) {
            return base.Channel.createGameLobbyAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.createGameLobbyResponse> createGameLobbyAsync(string playerID, string gameLobbyName) {
            LePrAtos.GameManagerService.createGameLobbyRequest inValue = new LePrAtos.GameManagerService.createGameLobbyRequest();
            inValue.playerID = playerID;
            inValue.gameLobbyName = gameLobbyName;
            return ((LePrAtos.GameManagerService.GameManager)(this)).createGameLobbyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.setGameLobbyNameResponse LePrAtos.GameManagerService.GameManager.setGameLobbyName(LePrAtos.GameManagerService.setGameLobbyNameRequest request) {
            return base.Channel.setGameLobbyName(request);
        }
        
        public void setGameLobbyName(string playerID, string GameLobbyID, string gameLobbyName) {
            LePrAtos.GameManagerService.setGameLobbyNameRequest inValue = new LePrAtos.GameManagerService.setGameLobbyNameRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.gameLobbyName = gameLobbyName;
            LePrAtos.GameManagerService.setGameLobbyNameResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).setGameLobbyName(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.setGameLobbyNameResponse> LePrAtos.GameManagerService.GameManager.setGameLobbyNameAsync(LePrAtos.GameManagerService.setGameLobbyNameRequest request) {
            return base.Channel.setGameLobbyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.setGameLobbyNameResponse> setGameLobbyNameAsync(string playerID, string GameLobbyID, string gameLobbyName) {
            LePrAtos.GameManagerService.setGameLobbyNameRequest inValue = new LePrAtos.GameManagerService.setGameLobbyNameRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.gameLobbyName = gameLobbyName;
            return ((LePrAtos.GameManagerService.GameManager)(this)).setGameLobbyNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.setPlayerLimitResponse LePrAtos.GameManagerService.GameManager.setPlayerLimit(LePrAtos.GameManagerService.setPlayerLimitRequest request) {
            return base.Channel.setPlayerLimit(request);
        }
        
        public void setPlayerLimit(string playerID, string GameLobbyID, int playerLimit) {
            LePrAtos.GameManagerService.setPlayerLimitRequest inValue = new LePrAtos.GameManagerService.setPlayerLimitRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.playerLimit = playerLimit;
            LePrAtos.GameManagerService.setPlayerLimitResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).setPlayerLimit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.setPlayerLimitResponse> LePrAtos.GameManagerService.GameManager.setPlayerLimitAsync(LePrAtos.GameManagerService.setPlayerLimitRequest request) {
            return base.Channel.setPlayerLimitAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.setPlayerLimitResponse> setPlayerLimitAsync(string playerID, string GameLobbyID, int playerLimit) {
            LePrAtos.GameManagerService.setPlayerLimitRequest inValue = new LePrAtos.GameManagerService.setPlayerLimitRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.playerLimit = playerLimit;
            return ((LePrAtos.GameManagerService.GameManager)(this)).setPlayerLimitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.kickPlayerResponse LePrAtos.GameManagerService.GameManager.kickPlayer(LePrAtos.GameManagerService.kickPlayerRequest request) {
            return base.Channel.kickPlayer(request);
        }
        
        public void kickPlayer(string playerID, string GameLobbyID, string username) {
            LePrAtos.GameManagerService.kickPlayerRequest inValue = new LePrAtos.GameManagerService.kickPlayerRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.username = username;
            LePrAtos.GameManagerService.kickPlayerResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).kickPlayer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.kickPlayerResponse> LePrAtos.GameManagerService.GameManager.kickPlayerAsync(LePrAtos.GameManagerService.kickPlayerRequest request) {
            return base.Channel.kickPlayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.kickPlayerResponse> kickPlayerAsync(string playerID, string GameLobbyID, string username) {
            LePrAtos.GameManagerService.kickPlayerRequest inValue = new LePrAtos.GameManagerService.kickPlayerRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.username = username;
            return ((LePrAtos.GameManagerService.GameManager)(this)).kickPlayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.joinGameLobbyResponse LePrAtos.GameManagerService.GameManager.joinGameLobby(LePrAtos.GameManagerService.joinGameLobbyRequest request) {
            return base.Channel.joinGameLobby(request);
        }
        
        public LePrAtos.GameManagerService.gameLobby joinGameLobby(string playerID, string GameLobbyID, string gameLobbyPassword) {
            LePrAtos.GameManagerService.joinGameLobbyRequest inValue = new LePrAtos.GameManagerService.joinGameLobbyRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.gameLobbyPassword = gameLobbyPassword;
            LePrAtos.GameManagerService.joinGameLobbyResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).joinGameLobby(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.joinGameLobbyResponse> LePrAtos.GameManagerService.GameManager.joinGameLobbyAsync(LePrAtos.GameManagerService.joinGameLobbyRequest request) {
            return base.Channel.joinGameLobbyAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.joinGameLobbyResponse> joinGameLobbyAsync(string playerID, string GameLobbyID, string gameLobbyPassword) {
            LePrAtos.GameManagerService.joinGameLobbyRequest inValue = new LePrAtos.GameManagerService.joinGameLobbyRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            inValue.gameLobbyPassword = gameLobbyPassword;
            return ((LePrAtos.GameManagerService.GameManager)(this)).joinGameLobbyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.leaveGameLobbyResponse LePrAtos.GameManagerService.GameManager.leaveGameLobby(LePrAtos.GameManagerService.leaveGameLobbyRequest request) {
            return base.Channel.leaveGameLobby(request);
        }
        
        public void leaveGameLobby(string playerID, string GameLobbyID) {
            LePrAtos.GameManagerService.leaveGameLobbyRequest inValue = new LePrAtos.GameManagerService.leaveGameLobbyRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            LePrAtos.GameManagerService.leaveGameLobbyResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).leaveGameLobby(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.leaveGameLobbyResponse> LePrAtos.GameManagerService.GameManager.leaveGameLobbyAsync(LePrAtos.GameManagerService.leaveGameLobbyRequest request) {
            return base.Channel.leaveGameLobbyAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.leaveGameLobbyResponse> leaveGameLobbyAsync(string playerID, string GameLobbyID) {
            LePrAtos.GameManagerService.leaveGameLobbyRequest inValue = new LePrAtos.GameManagerService.leaveGameLobbyRequest();
            inValue.playerID = playerID;
            inValue.GameLobbyID = GameLobbyID;
            return ((LePrAtos.GameManagerService.GameManager)(this)).leaveGameLobbyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.getGameLobbyResponse LePrAtos.GameManagerService.GameManager.getGameLobby(LePrAtos.GameManagerService.getGameLobbyRequest request) {
            return base.Channel.getGameLobby(request);
        }
        
        public LePrAtos.GameManagerService.gameLobby getGameLobby(string GameLobbyID) {
            LePrAtos.GameManagerService.getGameLobbyRequest inValue = new LePrAtos.GameManagerService.getGameLobbyRequest();
            inValue.GameLobbyID = GameLobbyID;
            LePrAtos.GameManagerService.getGameLobbyResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).getGameLobby(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.getGameLobbyResponse> LePrAtos.GameManagerService.GameManager.getGameLobbyAsync(LePrAtos.GameManagerService.getGameLobbyRequest request) {
            return base.Channel.getGameLobbyAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.getGameLobbyResponse> getGameLobbyAsync(string GameLobbyID) {
            LePrAtos.GameManagerService.getGameLobbyRequest inValue = new LePrAtos.GameManagerService.getGameLobbyRequest();
            inValue.GameLobbyID = GameLobbyID;
            return ((LePrAtos.GameManagerService.GameManager)(this)).getGameLobbyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.getGameLobbiesResponse LePrAtos.GameManagerService.GameManager.getGameLobbies(LePrAtos.GameManagerService.getGameLobbiesRequest request) {
            return base.Channel.getGameLobbies(request);
        }
        
        public LePrAtos.GameManagerService.gameLobby[] getGameLobbies() {
            LePrAtos.GameManagerService.getGameLobbiesRequest inValue = new LePrAtos.GameManagerService.getGameLobbiesRequest();
            LePrAtos.GameManagerService.getGameLobbiesResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).getGameLobbies(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.getGameLobbiesResponse> LePrAtos.GameManagerService.GameManager.getGameLobbiesAsync(LePrAtos.GameManagerService.getGameLobbiesRequest request) {
            return base.Channel.getGameLobbiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.getGameLobbiesResponse> getGameLobbiesAsync() {
            LePrAtos.GameManagerService.getGameLobbiesRequest inValue = new LePrAtos.GameManagerService.getGameLobbiesRequest();
            return ((LePrAtos.GameManagerService.GameManager)(this)).getGameLobbiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.getPlayerByIDResponse LePrAtos.GameManagerService.GameManager.getPlayerByID(LePrAtos.GameManagerService.getPlayerByIDRequest request) {
            return base.Channel.getPlayerByID(request);
        }
        
        public LePrAtos.GameManagerService.player getPlayerByID(string playerID) {
            LePrAtos.GameManagerService.getPlayerByIDRequest inValue = new LePrAtos.GameManagerService.getPlayerByIDRequest();
            inValue.playerID = playerID;
            LePrAtos.GameManagerService.getPlayerByIDResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).getPlayerByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.getPlayerByIDResponse> LePrAtos.GameManagerService.GameManager.getPlayerByIDAsync(LePrAtos.GameManagerService.getPlayerByIDRequest request) {
            return base.Channel.getPlayerByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.getPlayerByIDResponse> getPlayerByIDAsync(string playerID) {
            LePrAtos.GameManagerService.getPlayerByIDRequest inValue = new LePrAtos.GameManagerService.getPlayerByIDRequest();
            inValue.playerID = playerID;
            return ((LePrAtos.GameManagerService.GameManager)(this)).getPlayerByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LePrAtos.GameManagerService.setPlayerStatusResponse LePrAtos.GameManagerService.GameManager.setPlayerStatus(LePrAtos.GameManagerService.setPlayerStatusRequest request) {
            return base.Channel.setPlayerStatus(request);
        }
        
        public void setPlayerStatus(string playerID, bool status) {
            LePrAtos.GameManagerService.setPlayerStatusRequest inValue = new LePrAtos.GameManagerService.setPlayerStatusRequest();
            inValue.playerID = playerID;
            inValue.status = status;
            LePrAtos.GameManagerService.setPlayerStatusResponse retVal = ((LePrAtos.GameManagerService.GameManager)(this)).setPlayerStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LePrAtos.GameManagerService.setPlayerStatusResponse> LePrAtos.GameManagerService.GameManager.setPlayerStatusAsync(LePrAtos.GameManagerService.setPlayerStatusRequest request) {
            return base.Channel.setPlayerStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<LePrAtos.GameManagerService.setPlayerStatusResponse> setPlayerStatusAsync(string playerID, bool status) {
            LePrAtos.GameManagerService.setPlayerStatusRequest inValue = new LePrAtos.GameManagerService.setPlayerStatusRequest();
            inValue.playerID = playerID;
            inValue.status = status;
            return ((LePrAtos.GameManagerService.GameManager)(this)).setPlayerStatusAsync(inValue);
        }
    }
}
