//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LePrAtos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LePrAtos.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionHandling_Caption.
        /// </summary>
        public static string ExceptionHandling_Caption {
            get {
                return ResourceManager.GetString("ExceptionHandling_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionHandling_Message.
        /// </summary>
        public static string ExceptionHandling_Message {
            get {
                return ResourceManager.GetString("ExceptionHandling_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_CreatedByTempalte.
        /// </summary>
        public static string LobbyBrowser_CreatedByTempalte {
            get {
                return ResourceManager.GetString("LobbyBrowser_CreatedByTempalte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_CreateLobby.
        /// </summary>
        public static string LobbyBrowser_CreateLobby {
            get {
                return ResourceManager.GetString("LobbyBrowser_CreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_GameName.
        /// </summary>
        public static string LobbyBrowser_GameName {
            get {
                return ResourceManager.GetString("LobbyBrowser_GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_HasPassword.
        /// </summary>
        public static string LobbyBrowser_HasPassword {
            get {
                return ResourceManager.GetString("LobbyBrowser_HasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_JoinFullLobby.
        /// </summary>
        public static string LobbyBrowser_JoinFullLobby {
            get {
                return ResourceManager.GetString("LobbyBrowser_JoinFullLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_JoinLobby.
        /// </summary>
        public static string LobbyBrowser_JoinLobby {
            get {
                return ResourceManager.GetString("LobbyBrowser_JoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_JoinLobbyFailed.
        /// </summary>
        public static string LobbyBrowser_JoinLobbyFailed {
            get {
                return ResourceManager.GetString("LobbyBrowser_JoinLobbyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_JoinLobbyFailed.
        /// </summary>
        public static string LobbyBrowser_JoinLobbyFailed1 {
            get {
                return ResourceManager.GetString("LobbyBrowser_JoinLobbyFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_Logout.
        /// </summary>
        public static string LobbyBrowser_Logout {
            get {
                return ResourceManager.GetString("LobbyBrowser_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_MaxPlayers.
        /// </summary>
        public static string LobbyBrowser_MaxPlayers {
            get {
                return ResourceManager.GetString("LobbyBrowser_MaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_NumberPlayers.
        /// </summary>
        public static string LobbyBrowser_NumberPlayers {
            get {
                return ResourceManager.GetString("LobbyBrowser_NumberPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_SearchText.
        /// </summary>
        public static string LobbyBrowser_SearchText {
            get {
                return ResourceManager.GetString("LobbyBrowser_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_ShowFull.
        /// </summary>
        public static string LobbyBrowser_ShowFull {
            get {
                return ResourceManager.GetString("LobbyBrowser_ShowFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_ShowProtected.
        /// </summary>
        public static string LobbyBrowser_ShowProtected {
            get {
                return ResourceManager.GetString("LobbyBrowser_ShowProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_WrongLobbyPassword.
        /// </summary>
        public static string LobbyBrowser_WrongLobbyPassword {
            get {
                return ResourceManager.GetString("LobbyBrowser_WrongLobbyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_ApplySettings.
        /// </summary>
        public static string LobbyView_ApplySettings {
            get {
                return ResourceManager.GetString("LobbyView_ApplySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_LeaveLobby.
        /// </summary>
        public static string LobbyView_LeaveLobby {
            get {
                return ResourceManager.GetString("LobbyView_LeaveLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_LimitLowerThanCount.
        /// </summary>
        public static string LobbyView_LimitLowerThanCount {
            get {
                return ResourceManager.GetString("LobbyView_LimitLowerThanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_LobbyPassword.
        /// </summary>
        public static string LobbyView_LobbyPassword {
            get {
                return ResourceManager.GetString("LobbyView_LobbyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_NewLobbySettings.
        /// </summary>
        public static string LobbyView_NewLobbySettings {
            get {
                return ResourceManager.GetString("LobbyView_NewLobbySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_Owner.
        /// </summary>
        public static string LobbyView_Owner {
            get {
                return ResourceManager.GetString("LobbyView_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_Ready.
        /// </summary>
        public static string LobbyView_Ready {
            get {
                return ResourceManager.GetString("LobbyView_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_ReallyQuit.
        /// </summary>
        public static string LobbyView_ReallyQuit {
            get {
                return ResourceManager.GetString("LobbyView_ReallyQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_Remove.
        /// </summary>
        public static string LobbyView_Remove {
            get {
                return ResourceManager.GetString("LobbyView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_RemovePassword.
        /// </summary>
        public static string LobbyView_RemovePassword {
            get {
                return ResourceManager.GetString("LobbyView_RemovePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_StartGame.
        /// </summary>
        public static string LobbyView_StartGame {
            get {
                return ResourceManager.GetString("LobbyView_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_YouGotRemoved.
        /// </summary>
        public static string LobbyView_YouGotRemoved {
            get {
                return ResourceManager.GetString("LobbyView_YouGotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_AlreadyLoggedIn.
        /// </summary>
        public static string LoginView_AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("LoginView_AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_ApplyOnRestart.
        /// </summary>
        public static string LoginView_ApplyOnRestart {
            get {
                return ResourceManager.GetString("LoginView_ApplyOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_BadLogin.
        /// </summary>
        public static string LoginView_BadLogin {
            get {
                return ResourceManager.GetString("LoginView_BadLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Language.
        /// </summary>
        public static string LoginView_Language {
            get {
                return ResourceManager.GetString("LoginView_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Register.
        /// </summary>
        public static string LoginView_Register {
            get {
                return ResourceManager.GetString("LoginView_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_ResetPassword.
        /// </summary>
        public static string LoginView_ResetPassword {
            get {
                return ResourceManager.GetString("LoginView_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Restart.
        /// </summary>
        public static string LoginView_Restart {
            get {
                return ResourceManager.GetString("LoginView_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_SaveLogin.
        /// </summary>
        public static string LoginView_SaveLogin {
            get {
                return ResourceManager.GetString("LoginView_SaveLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Theme.
        /// </summary>
        public static string LoginView_Theme {
            get {
                return ResourceManager.GetString("LoginView_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_UsernameOrMail.
        /// </summary>
        public static string LoginView_UsernameOrMail {
            get {
                return ResourceManager.GetString("LoginView_UsernameOrMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoPermissions.
        /// </summary>
        public static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterView_BadRegister.
        /// </summary>
        public static string RegisterView_BadRegister {
            get {
                return ResourceManager.GetString("RegisterView_BadRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterView_Register.
        /// </summary>
        public static string RegisterView_Register {
            get {
                return ResourceManager.GetString("RegisterView_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterView_RepeatPassword.
        /// </summary>
        public static string RegisterView_RepeatPassword {
            get {
                return ResourceManager.GetString("RegisterView_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterView_Title.
        /// </summary>
        public static string RegisterView_Title {
            get {
                return ResourceManager.GetString("RegisterView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword_Code.
        /// </summary>
        public static string ResetPassword_Code {
            get {
                return ResourceManager.GetString("ResetPassword_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword_NewPassword.
        /// </summary>
        public static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword_PasswordChanged.
        /// </summary>
        public static string ResetPassword_PasswordChanged {
            get {
                return ResourceManager.GetString("ResetPassword_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword_RequestReset.
        /// </summary>
        public static string ResetPassword_RequestReset {
            get {
                return ResourceManager.GetString("ResetPassword_RequestReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword_SetPassword.
        /// </summary>
        public static string ResetPassword_SetPassword {
            get {
                return ResourceManager.GetString("ResetPassword_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextValidationRule_ForbiddenChar.
        /// </summary>
        public static string TextValidationRule_ForbiddenChar {
            get {
                return ResourceManager.GetString("TextValidationRule_ForbiddenChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextValidationRule_Lenght.
        /// </summary>
        public static string TextValidationRule_Length {
            get {
                return ResourceManager.GetString("TextValidationRule_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextValidationRule_MailaddressAlreadyTaken.
        /// </summary>
        public static string TextValidationRule_MailaddressAlreadyTaken {
            get {
                return ResourceManager.GetString("TextValidationRule_MailaddressAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextValidationRule_MailValid.
        /// </summary>
        public static string TextValidationRule_MailValid {
            get {
                return ResourceManager.GetString("TextValidationRule_MailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextValidationRule_Mandatory.
        /// </summary>
        public static string TextValidationRule_Mandatory {
            get {
                return ResourceManager.GetString("TextValidationRule_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextValidationRule_UsernameAlreadyTaken.
        /// </summary>
        public static string TextValidationRule_UsernameAlreadyTaken {
            get {
                return ResourceManager.GetString("TextValidationRule_UsernameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
