//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LePrAtos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LePrAtos.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_CreateLobby.
        /// </summary>
        public static string LobbyBrowser_CreateLobby {
            get {
                return ResourceManager.GetString("LobbyBrowser_CreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_GameName.
        /// </summary>
        public static string LobbyBrowser_GameName {
            get {
                return ResourceManager.GetString("LobbyBrowser_GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_HasPassword.
        /// </summary>
        public static string LobbyBrowser_HasPassword {
            get {
                return ResourceManager.GetString("LobbyBrowser_HasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_JoinLobby.
        /// </summary>
        public static string LobbyBrowser_JoinLobby {
            get {
                return ResourceManager.GetString("LobbyBrowser_JoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_Logout.
        /// </summary>
        public static string LobbyBrowser_Logout {
            get {
                return ResourceManager.GetString("LobbyBrowser_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyBrowser_NumberPlayers.
        /// </summary>
        public static string LobbyBrowser_NumberPlayers {
            get {
                return ResourceManager.GetString("LobbyBrowser_NumberPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_LeaveLobby.
        /// </summary>
        public static string LobbyView_LeaveLobby {
            get {
                return ResourceManager.GetString("LobbyView_LeaveLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_Owner.
        /// </summary>
        public static string LobbyView_Owner {
            get {
                return ResourceManager.GetString("LobbyView_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_Ready.
        /// </summary>
        public static string LobbyView_Ready {
            get {
                return ResourceManager.GetString("LobbyView_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_Remove.
        /// </summary>
        public static string LobbyView_Remove {
            get {
                return ResourceManager.GetString("LobbyView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_StartGame.
        /// </summary>
        public static string LobbyView_StartGame {
            get {
                return ResourceManager.GetString("LobbyView_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LobbyView_Username.
        /// </summary>
        public static string LobbyView_Username {
            get {
                return ResourceManager.GetString("LobbyView_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Language.
        /// </summary>
        public static string LoginView_Language {
            get {
                return ResourceManager.GetString("LoginView_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Password.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_SaveLogin.
        /// </summary>
        public static string LoginView_SaveLogin {
            get {
                return ResourceManager.GetString("LoginView_SaveLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginView_Username.
        /// </summary>
        public static string LoginView_Username {
            get {
                return ResourceManager.GetString("LoginView_Username", resourceCulture);
            }
        }
    }
}
